### PR TITLE
Fix/fix ui and remove ex bug

### PR DESCRIPTION
**Pull request by therizhao**

### CODE REVIEW

**Comment by therizhao** [comment]
Closes #187 , fix remove ex bug, ui improvements

**Review by youaremysky99 — DISMISSED** [review]
LGTM

**Review by WhiteLio — APPROVED** [review]
i hope this works HAHA

**Comment by WhiteLio** [comment]
might want to add the expected result (all related logs edited/deleted) to the UG so ppl dun report as bug haha

**Comment by therizhao** [comment]
Closes #187

**Pull request merged**
